### ISSUE TITLE
`gps pull` (and/or `gps ls remote`) - display titles "patches" of new additions

### ISSUE THREAD

**Issue by ctsstc** [uptech/git-ps-rs#134]
As a developer I would like to see a list of patches that are incoming when I run: `gps pull`

Essentially this would be like seeing a `gps ls` showing differences between the local and remote.

Maybe an interesting command would be to have `gps ls remote` which would display the patches up on the main remote that are not yet integrated to the local branch. Then the `gps ls remote` feature could be reused and ran before the gps pull.

**Comment by drewdeponte** [comment]
This should include the patch summary, the author of the patch, associated tickets of the patch in the integrated order.

This will make it useful if you are a tech lead to not only see patches that might be related to work you are doing like everyone else, but also to be able to see patches made by juniors/mentees so that you can keep up on those and review them as them come through.

**Comment by drewdeponte** [comment]
This has been integrated into mainline so I am closing this issue.
