### ISSUE TITLE
`gps int` with range

### ISSUE THREAD

**Issue by ctsstc** [uptech/git-ps-rs#142]
As a user of git ps, it would be nice to have an integrate option with a range when you're trying to push up multiple stacks.

ie: `gps int 0-3`

I believe this has more value when the isolate takes some time to run, this way you could grab a cup of coffee while builds and tests are running instead of babysitting it. Of course it could fail during this, but at least hopefully it would make it through some before hitting a patch that fails the isolate.

**Comment by drewdeponte** [comment]
There would be two possible approaches to implementing this that I can think of.

1. have all the patches cherry-picked into the isolate verification branch. The downside to this is we would lose the ability to verify that each of the patches are isolated. The benefit I guess would be that you would only have to wait for one isolation verification to run. This seems like a bad idea because it would allow non-isolated patches into your tree.
2. Have it do the isolation verification one patch at a time and just handle the integration of the series for you. In theory this could work. Though often I run into isolation verification issues as I move to other patches. So it would likely fail in teh middle of theh range.

In general I question the value of this feature. Generally, you shouldn't have a bunch of patches in your stack that you want to integrate all at once. If you are in that situation you aren't following the Patch Stack methodology. In the Patch Stack methodology you should be integrating your patches as you finish them.

**Comment by drewdeponte** [comment]
This has been integrated into mainline already. Therefore I am closing this issue.
