### ISSUE TITLE
Aid in preventing accidental publishing of patches

### ISSUE THREAD

**Issue by drewdeponte** [uptech/git-ps-rs#27]
The previous incarnation of git-ps had a check built-in where it would require that a patch has had a review requested prior to allowing you to publish the patch unless you provide the `-f` force option. In which case it would bypass that check.

We got feedback from numerous people with the previous incarnation that this wasn't good enough. So now I am contemplating doing that check but in addition maybe adding a prompt that presents the patch details and prompts the user if they are sure they want to publish the patch.

Maybe the combination of the two checks would be enough.

**Comment by ctsstc** [comment]
I personally have not used the force option that I can remember. Lately I've been performing my merges through Github's interface and then pulling back down, and even something trivial that I would like to get into the main branch I still create a pull request for.

I think the main concern I would have is if the patch had "changed", but I guess there's no initial state since it would not have a review requested.

Maybe on the last project this need came up to help publish releases when you're generating change logs and bumping version numbers like in `package.json`.

I think a good middle ground would be to introduce an interface that catches this case and prompts the user for confirmation.

**Comment by philipcolejohnson** [comment]
I haven't seen the feedback, so I'm curious what is happening that prompts the desire for more checks? If a user is prevented from publishing without getting a review (and assuming that check always works—I saw Ryan was somehow able to do it without an `rr` command), that seems like a pretty hard requirement.

So I'm assuming it's happening after a review is requested, when someone requested a review, but then they accidentally publish the patch before they want to? In that case, I think it does make sense to display commit information and then prompt if they want to continue publishing (maybe with a default 'no').

Two other ideas I had from this question:
 1. we could walk them through a sort of wizard when publishing. As in questions like `would you like to update this commit message?` and `you're pushing to origin/main. would you like to change the destination?` Something like that. It would prevent cli mistakes, give a user options, and make sure they know exactly what's happening.
 2. since we have patch statuses, maybe we could lean into it even more and give the user the ability to manually update the patch status. For example, if your pull request is rejected, you could maybe mark the patch backward to `branch` instead of `rr`, so that locally you are prevented from publishing. i guess maybe you could mark one as accepted, too, if you didn't want to push yet for some reason; we could theoretically even require them to mark as accepted before they are able to publish, which would prevent accidents.

**Comment by drewdeponte** [comment]
@philipcolejohnson your idea has got me thinking. One thing I was talking to @swiftymf about earlier today was having the request-review hooks. Maybe a pre hook and post hook where the `request-review-pre-hook` would get called before the process and could prevent the process from moving forward if it wasn't sucessful. This couldd be used to do things like run test suite, etc. to make sure it is good to `request-review`. The `request-review-post-hook` could then be used to actually do the creation of the pull request via GitHub CLI or some other program.

Maybe we could do something similar with hooks for the `integrate` command where there is an `integrate-pre-hook` that could check the state of the pull request and return a status indicating if it is ok or not. Then people could actually not being able to integrate a patch until that PR is actually approved.

**Comment by ctsstc** [comment]
On Phil's 2nd item I like the idea, you could have it pull in a CI status which would also include if the reviewer accepted or rejected it. This seems like it starts to step into the area of Pullwalla a bit. 

Since this would be platform specific like Github/Bitbucket, I would push this towards the idea of hooks and plugins for git ps. I do not think this would be core functionality, but being able to hook into this part of git ps may be interesting, or maybe it's too much?

**Comment by ctsstc** [comment]
I forgot to mention this on the last post. I'm not sure if there's something in Rust like the Prompts JS package, but it would make for a nice CLI interface.

https://github.com/terkelg/prompts#readme

## Interactive Confirmation
![](https://github.com/terkelg/prompts/raw/master/media/toggle.gif)

## Interactive select
![](https://github.com/terkelg/prompts/raw/master/media/select.gif)

## Autocomplete
![](https://github.com/terkelg/prompts/raw/master/media/autocomplete.gif)

**Comment by drewdeponte** [comment]
@ctsstc in terms of the verbosity. That is all gone. The Rust version opts more minimal output until an error occurs and then it can be verbose.

Also their are ports of that prompts library to Rust as well as other similar libraries so doing interactive prompts if we want shouldn't be too hard.

**Comment by RyanHedges** [comment]
I have accidentally `pub`ed more patches than I care to admit. Mostly because I have a stack of patches that have already been requested. I typo the wrong index, I misremember a rebase I did that changed the order, or I'm just going way too fast. This feels like a think fast think slow situation. Branch names, in some situations, have a way of slowing you down if doing a merge. You read the branch name, your know what's mostly in it. I see an index, I have to make sure I `ls` the stack to be sure. 

So a prompt that simply says "are you sure?" And then spits out the patch info would be helpful to me. I know it would be annoying to some peoples work flow, but I personally would appreciate git ps slowing me down, especially in rapid fire `pub` mode.

The hooks are a clever idea for remote repos, ci's, and such too! But I'd still want a prompt.

This also feels like another reason to have a git ps config. I want to have the default prompt, someone else can git ps config to disable prompts because they like going fast and living on the edge!

**Comment by drewdeponte** [comment]
Yeah I guess the right thing to do is to have a config with a value for controlling if it prompts you or not.

This config probably should be able to have a global config in the users home directory, `~/.config/git-ps/config.toml` as well as a local config to the project, `.git/git-ps/config.toml` and then it needs to merge those together having the project specific one override the global ones.

I am not sure what other use cases we really have for this config other than this one at the moment. Maybe if we decided to support the ls after pull concept or something we could make that a configuration as well.

```
[request-review]
require-user-verification=false // default: true

[pull]
show-list-post-pull=true // default: false
```

Maybe it could be something along those lines and it would I guess lay the foundation so that it would be easier to add things that require configuration in the future if we run into them.

**Comment by drewdeponte** [comment]
I have created an issue specifically for the config support, issue #37 .

So this issue now depends on that being completed.

**Comment by drewdeponte** [comment]
This has been integrated into mainline so I am closing this issue.
