### ISSUE TITLE
Add config file support

### ISSUE THREAD

**Issue by drewdeponte** [uptech/git-ps-rs#37]
We need a config system to be added so that users can use it to control certain aspects of behavior of git patch stack.

This originated as part of discussion is issue #27 where I wrote the following:

> Yeah I guess the right thing to do is to have a config with a value for controlling if it prompts you or not.
>
>This config probably should be able to have a global config in the users home directory, `~/.config/git-ps/config.toml` as well as a >local config to the project, `.git/git-ps/config.toml` and then it needs to merge those together having the project specific one >override the global ones.
>
>I am not sure what other use cases we really have for this config other than this one at the moment. Maybe if we decided to >support the ls after pull concept or something we could make that a configuration as well.
>
>```
>[request-review]
>require-user-verification=false // default: true
>
>[pull]
>show-list-post-pull=true // default: false
>```
>
>Maybe it could be something along those lines and it would I guess lay the foundation so that it would be easier to add things that >require configuration in the future if we run into them.

**Comment by RyanHedges** [comment]
Really cool option
- Merge repo with local. If the repo config doesn't have a preference for how the `pub` command should run, then it uses personal. If the repo does have a config for `pub`, use that instead of preference. 

Expected behavior from other config features
- if repo has a config, use only that, if no repo config, go up to next layer, aka personal. I think having personal trump repo configs is a little unexpected. specific config (repo) is used over generic (personal).

**Comment by drewdeponte** [comment]
Yeah, I think what I am netting on is that there are three that get merged together to create the config that the app uses.

 * `~/.config/git-ps/config.toml` - intended for personal preferences
 * `.git/git-ps/config.toml` - intended for personal preferences specific to a repository (trumps the one above)
 * `root-of-repo/.git-ps/config.toml` - intended for share configurations unique to a repo but shared across all contributors (trumps the above)

**Comment by drewdeponte** [comment]
This has been integrated into mainline so I am closing this issue.
