### ISSUE TITLE
`Error: GetCommitDiffPatchIdFailed(GetDiffFailed(MergeCommit))` on `gps ls`

### ISSUE THREAD

**Issue by brandonpittman** [uptech/git-ps-rs#53]
I've been using the old `git ps` without issue, but after setting up the new version, I immediately got this error:

```
Error: GetCommitDiffPatchIdFailed(GetDiffFailed(MergeCommit))
```

Regular old `master` branch that `git ps ls` displayed patches on just fine.

**Comment by brandonpittman** [comment]
Figured it out. There was a rebase-merge directory. The `gps pull` command gave a better error message that led me to the fix.

**Comment by drewdeponte** [comment]
Thanks @brandonpittman we have all the errors propagating but don't have them mapped to human readable error messages just yet.

At some point soon we should probably start working on mapping the errors to human readable error messages rather than just the derived debug representation of the errors.

**Comment by brandonpittman** [comment]
@drewdeponte Sorry for not trying to figure it out on my own first. The new version is so much faster. Ran it on a branch with 80 patches (don't ask). The `git ps ls` speed vs. `gps ls` speed was night and day.

**Comment by drewdeponte** [comment]
No worries. Yeah we largely have Rust and libgit2 to thank for the performance gains.
