### ISSUE TITLE
Call `git-ps ls` after `git-ps pull`

### ISSUE THREAD

**Issue by drewjbartlett** [uptech/git-ps-rs#8]
Currently whenever I called `git-ps pull` I usually end up having to call `git-ps ls` after since the stack has changed. Or I just do `git-ps pull && git-ps ls` in a single call so I can see the updated stack.

**Comment by drewdeponte** [comment]
One thing I have been talking with other people about on this front is exposing additional commands that are lower level (plumbing) commands if you will to facilitate people being able to easily configure **shell aliases** or **scripts**.

I know this isn't necessarily answering this specific request. But what do you think about this stance in general? Should we provide examples of zsh aliases or something?

My take so far is that I think we should provide these lower level (plumbing) commands because it opens up the scriptability of different workflows with Git Patch Stack.

**Comment by drewdeponte** [comment]
Once we have issue #37 maybe this is something that could be added just as a configuration.

**Comment by drewdeponte** [comment]
This has been integrated into mainline therefore I am closing this issue.
