### ISSUE TITLE
More information on patch state info

### ISSUE THREAD

**Issue by ctsstc** [uptech/git-ps-rs#83]
I was hoping to find out more about what patch states there were and what they meant, but there's nothing in the README or listed when running `gps ls --help`.

For instance I have: `rr+!` after squashing a commit into a patch that already had a review up and then ran `sync`.

**Comment by drewdeponte** [comment]
@ctsstc this is an excellent ticket. We definitely need to add better explanation in the `list` commands help messaging.

The `rr` indicates that the patch has previously been requested review. The `+` indicates that the local patch has changed since you last requested review and the `!` indicates that the remote patch has changed since you last requested review.

**Comment by drewdeponte** [comment]
I am closing this issue as it has been integrated into mainline.
