### ISSUE TITLE
Checkout patch branch by patch index (isolate command)

### ISSUE THREAD

**Issue by RyanHedges** [uptech/git-ps-rs#9]
I wanted to quickly test the build-ability and test-ability of a patch outside of the context of my local main branch stack. Basically have it build it against origin/main
* Running `git-ps co 3` moves `HEAD` to that commit, but is still basing it off of my other patches on my stack. Including changes that may not be there when this PR is merged.
* I can checkout out my branch if I've requested a review with `git checkout ps/rr/my_branch` but I have to look up the generated branch name.
    *  If I haven't requested a review, I cannot do this.
* I can `git-ps rebase` my stack, move the commit around, and then `git-ps co 0` to see it, but that seems like more work than it's worth and may be error prone.
* I can create a new local branch and cherrypick the commit to it, but this problem seems like something that git-ps can help do for me given the other things it helps me do today.

### Here are my assumptions for a solution:
* Interacting with the patch index is ideal and not having to deal with the branches is ideal. For example, `git-ps co 0` let's you not care about commit shas are branch names, but leverage the index shown in `git-ps ls`.
* Should work regardless of request review status of patch.

###  For an interface I could imagine
* `git-ps co 3 -h`: `-h` to flag that you want the commit at patch-index 3 to be based on origin/HEAD.
* `git-ps b 3`: `b` or `build` to signify you want to build this commit and therefor, get it based on origin/HEAD.
* `git-ps oh 3`: `oh` or `origin-head` to signify you want it based on origin/head.
* `git-ps co 3 origin/main`: Tell which patch you want to check out and where it should go, in this case `origin/main`
* `git-ps cmp 3 origin/main`: `cmp` or `compare` to compare the index onto another.

###### Solution:
* Running the CLI command creates a branch with temp in the name (e.g. `ps/temp/my_branch`).
    1. Run `git-ps co 3 origin/main` to start comand
    1. The new branch with `ps/temp/` prefix is based on `origin/main` similar to how `rr` command creates branches.
    1. The command checks out this new temp branch that's on origin/main.
    1. Do your testing, building, experimentation, etc.
    1. Go back to you stack
        * `git-ps co` goes back to the top of your stack
        * The command checks and removes any existing temp branches.
###### Challenges:
* Unsure if this is feasible given that stacks of patches can happen on `main` and any other branch. May have to keep track of what commit the command was ran on so you can go back to it.

###### Solution:
* Cherry pick a duplicate commit only origin/HEAD
    1. Run `git-ps cp 3 origin/main` (`cp` for "cherrypick") to cherrypick index 3 onto origin/main.
    2. update commit message to contain a temporary id `ps-temp-id: 4B71992D-B...`
    3. Do you testing, building, experimentation, etc.
    4. Go back to your stack
        * A command like`git-ps reset` signifies intent to remove everything.
        * Command checks to see if commit message contains temporary id.
        * once back on main, deletes the temp commit.

###### Challenges:
* Could create a lot of noise in your tree with no obvious ways to tell it's temporary like the branch does
* If something goes wrong, commits are still hanging there. Would have to implement a cleanup command to inspect commit messages and delete. So it feels a little kludgy.

Please let me know if there are other existing solutions that would make this feature request unnecessary! 🙏

**Comment by drewdeponte** [comment]
I either do the `git-ps rebase` with `git co 0` technique or I do a `git-ps rr <patch-index>` and `git checkout <branch-name>` without opening the actual pull request.

I can definitely see how these approaches are less than ideal and could definitely be streamlined.

One other approach I thought of to aid with cleanup of any temp branchs would be to have a command where you could give it another command to run and it would cleanup after itself effectively.

So imagine you do a `git-ps run <patch-index> <command>` and it would run the given command in the context of the that patch by doing exactly what you are saying. You could for example hand it a build & test command. When it is done it could then do all the cleanup and put you back exactly where you started.

Either way I defiintely think something like this is doable.

The other approach I considered was splitting the process into multiple steps.

1. `git-ps prep <patch-index>` - creates the branch, associates the patch to it, and cherry picks the patch into it
2. `git-ps push <patch-index>` - pushes the branch associated with the patch up to the remote
3. `git-ps rr <patch-index>` - maybe this could change to something that would fire an rr hook which could actually open the pull request for you without having to go to the webview either that or we keep its current meaning where it is really doing the `prep` and the `push` as a higher level command.
4. `git-ps co <patch-index>` - this would checkout the patch in the associated branc if a `prep` or `push` has happened

I think we could basically have these lower level commands to facilitate things but also have the higher level ones that do multiple of these steps.

**Comment by drewdeponte** [comment]
Ok, so @RyanHedges and I got on a call today and I think we have convinced ourselves that we should follow suite with Git and have a **plumbing** layer of commands as well as a **porcelain** layer of commands. The **porcelain** are just higher level conceptual commands that are built up from the **plumbing** commands.

We believe this design will make `git-ps` more friendly for people wanting to script their own custom higher level operations based on the **plumbing** commands.

The following are what we think the core **plumbing** commands should be & do.

* `git-ps branch <patch-index>` - creates a branch for the identified patch, associates the patch to the branch, and cherry picks the patch into it. Running this multiple times just overwrites the branch and commit with the new cherry-pick.
* `git-ps push <patch-index>` - checks if branch exists for the patch, if it doesn't it exits with failure. If a branch does exist for it then it pushes the branch up to the remote associated with the stack you are on.
* `git-ps verify-session-start` - records the currently checked out branch in the verify state, starting the "verify session"
* `git-ps checkout <patch-index>` - checks if a branch exists for the patch, if it doesn't it exits with failure. If a branch does exist for it, it then checks out the branch for that patch.
* `git-ps verify-session-end` - cleans up the verify state, ending the "verify session", and putting you back on the branch you were on when you started the "verify session"
* `git-ps delete-remote-branch <patch-index>` - check if the remote branch exists for the patch, if it does NOT then exit in failure, if it does delete it
* `git-ps delete-branch <patch-index>` - check if a local branch exists for the patch, if it does NOT then exit in failure, if it does delete it
* `git-ps delete <patch-index>` - trigger a non-interactive rebase where the patch itself gets dropped
* `git-ps publish <patch-index>` - check if a local branch exists for the patch, if it doesn NOT then exit in failure, if it does then publish to the current patch stack's upstream (e.g. origin/main) via `git push origin ps/rr/some-patch-rr-branch:main`

The following are what we think the **porcelain** command should be & do.

* `git-ps ls` -  list the stack of patches
* `git-ps show <patch-index>` - show the full patch and associated details
* `git-ps pull` - to fetch the state from the remote of the stack you are on and rebase the stack of patches onto it
* `git-ps rebase` - to interactive rebase the stack of patches
* `git-ps verify <patch-index>` - this should do the `git-ps branch`, `git-ps verify-session-start`, and the `git-ps checkout` so that you can see the state of the code base with that patch isolated and can make sure thit builds and 
* `git-ps verify reset` - this should do a `git-ps verify-session-end`
* `git-ps request-review <patch-index>` - this should do the `git-ps branch`, `git-ps push`, and fire a request review hook enabling users to use the hook to automate opening the pull request for them instead of having to click the link, open a browser, and click buttons to create the pull request.
* `git-ps integrate <patch-index>` - to integrate a patch into your current patch stack's upstream (e.g. origin/main). This should do `git-ps branch`, `git-ps push` to update remote state, and a `git-ps publish`
* `git-ps nuke <patch-index>` - it should do `git-ps delete-remote-branch`, `git-ps delete-branch`, `git-ps delete` effectively cleaning up all the related branches and deleting the patch itself

I used more full-name commands to try and communicate more clearly. We may decide to use these or abbreviations or both. But think this gets the idea across. I would love any feedback on this.

**Comment by RyanHedges** [comment]
Overall I think this makes sense. I do think there are some specifics that don't seem like they will play out exactly like it's described. Maybe driving out the **porcelain** commands a little more fully in dev will help identify the **plumbing** commands needed. I know you often work outside-in, but just calling it out.

Some questions and thoughts in no particular order:

* `git-ps ls`
    * Doesn't seem to have a supporting plumbing command. Maybe that's ok? Could see a plumbing command like `git-ps identify <patch-index>` to std out the info for that specific patch.
    * Could also include information about branch existing or not. It's assumed with the `rr` in the "review status" column. Maybe explicit in a "has branch" column with a `*` or something? Maybe it becomes too noisy. Basically distinguishing between having "requested a review" and a branch exists for the patch.
    * or maybe a plumbing command to can list all the info for a patch that can be parsed and conformed to `ls` structure.

* `git-ps delete <patch-index>`
    * Given this is the most "destructive" of the delete commands I wonder if we should make the name more special? Three commands start with `delete`. It may make for possible mistakes with autocomplete. Maybe `git-ps remove`, `git-ps destroy`? Maybe the others branch related ones have a different name `branch-delete-remote` and `branch-delete`? Especially since this runs as non interactive.
    * While a prompt might be more suited for `nuke`, maybe an "are you sure? (Y/N)" prompt that can be skipped?

* `git-ps publish <patch-index>`
    * Maybe this is `git-ps merge <patch-index>`? I like the current `pub` porcelain command that does the different steps for me. This publish does less (this doesn't delete branches like current `pub`).
    * Is the current `pub` no `integrate`?

* `git-ps verify reset`
   * Should this also do a `git-ps delete-branch`? I see the verify step as temporary, so I don't need the branch to exist locally when verify ends. When I want the branch I'm using a plumbing command, or I'm leveraging an existing branch from a `rr`. Do you see it differently? 

I really like the ability to use the plumbing commands to facilitate custom scripting. Could be good ways to test new ideas, and help people work in their specific flows. I'll keep thinking about this. Cool stuff @drewdeponte!

**Comment by RyanHedges** [comment]
Another thing to note...

I think one of the benefits of patch stack I've experienced is having to think about branches and branching strategies less and less, and have my mind think about the commits and small changes. Any of these commands that help facilitate thinking about branch names and branch management less is a plus for me. :)

**Comment by drewdeponte** [comment]
> * `git-ps ls`
>   
>   * Doesn't seem to have a supporting plumbing command. Maybe that's ok? Could see a plumbing command like `git-ps identify <patch-index>` to std out the info for that specific patch.
>   * Could also include information about branch existing or not. It's assumed with the `rr` in the "review status" column. Maybe explicit in a "has branch" column with a `*` or something? Maybe it becomes too noisy. Basically distinguishing between having "requested a review" and a branch exists for the patch.
>   * or maybe a plumbing command to can list all the info for a patch that can be parsed and conformed to `ls` structure.

I think this is ok for the time being. We can definitely break out additional plumbing commands over time. I think something like the `identify` idea or a command that outputs the information for the state of the patches could be useful. I think I will let this one continue to simmer over time.

> * `git-ps delete <patch-index>`
>   
>   * Given this is the most "destructive" of the delete commands I wonder if we should make the name more special? Three commands start with `delete`. It may make for possible mistakes with autocomplete. Maybe `git-ps remove`, `git-ps destroy`? Maybe the others branch related ones have a different name `branch-delete-remote` and `branch-delete`? Especially since this runs as non interactive.
>   * While a prompt might be more suited for `nuke`, maybe an "are you sure? (Y/N)" prompt that can be skipped?

Maybe we could call it `drop` so it is in alignment with the `drop` action in the interactive rebase. The branch related ones could stay delete which is in alignment with the git naming of commands. I agree that definitely could do things like prompt with the `nuke` command.

> * `git-ps publish <patch-index>`
>   
>   * Maybe this is `git-ps merge <patch-index>`? I like the current `pub` porcelain command that does the different steps for me. This publish does less (this doesn't delete branches like current `pub`).
>   * Is the current `pub` no `integrate`?

I want to avoid the term `merge` as it has relation to branches as a concept. The reason I switched `pub` to `integrate` was because I realized that it has natural alignment with Continuos Integration. Every time you run a `git ps integrate` you would performing the integration step of Continuous Integration.


> * `git-ps verify reset`
>   
>   * Should this also do a `git-ps delete-branch`? I see the verify step as temporary, so I don't need the branch to exist locally when verify ends. When I want the branch I'm using a plumbing command, or I'm leveraging an existing branch from a `rr`. Do you see it differently?

The `verify` concept is definitely an interesting one. When I was originally thinking about it I was thinking wit would just use the `branch` plumbing command which would create the request-review branch. As much as that would work. You might want to `verify` an updated patch and not have that branch updated. So I think you are right. Maybe we have a `ps/verify` branch which is created and deleted and you can only verify one patch at a time. So we will have to figure that out. Maybe we have specific `branch` plumbing commands, e.g. `branch-request-review` and `branch-verify` or something like that.

**Comment by drewdeponte** [comment]
The beginnings of this functionality has been added to mainline already as the `isolate (iso)` command. The core functionality of it is there.

However, we still need to add the state tracking and reseting of the checked out branch to fully complete this feature.

**Comment by drewdeponte** [comment]
I completed this functionality and it is in mainline.
